# Generated by Django 4.2.5 on 2023-10-04 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myTodoApp', '0002_remove_mytodoapp_user_user_bio_task_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='mytodoapp_user',
            managers=[
            ],
        ),
    ]
