# Generated by Django 4.2.5 on 2023-10-21 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myTodoApp', '0004_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.EmailField(default='NA', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
