# Generated by Django 4.2.5 on 2023-11-08 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myTodoApp', '0008_rename_user_task_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user_id',
            new_name='user',
        ),
    ]
